<a href="https://colab.research.google.com/github/KZoc/Kaggle-House_Prices_Predicting/blob/main/Notebook/House_Prices_Predicting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green>Data Description</font>

## Columns Descriptions:

MSSubClass: Identifies the type of dwelling involved in the sale.	

        20	1-STORY 1946 & NEWER ALL STYLES
        30	1-STORY 1945 & OLDER
        40	1-STORY W/FINISHED ATTIC ALL AGES
        45	1-1/2 STORY - UNFINISHED ALL AGES
        50	1-1/2 STORY FINISHED ALL AGES
        60	2-STORY 1946 & NEWER
        70	2-STORY 1945 & OLDER
        75	2-1/2 STORY ALL AGES
        80	SPLIT OR MULTI-LEVEL
        85	SPLIT FOYER
        90	DUPLEX - ALL STYLES AND AGES
       120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER
       150	1-1/2 STORY PUD - ALL AGES
       160	2-STORY PUD - 1946 & NEWER
       180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
       190	2 FAMILY CONVERSION - ALL STYLES AND AGES

MSZoning: Identifies the general zoning classification of the sale.
		
       A	Agriculture
       C	Commercial
       FV	Floating Village Residential
       I	Industrial
       RH	Residential High Density
       RL	Residential Low Density
       RP	Residential Low Density Park 
       RM	Residential Medium Density
	
LotFrontage: Linear feet of street connected to property

LotArea: Lot size in square feet

Street: Type of road access to property

       Grvl	Gravel	
       Pave	Paved
       	
Alley: Type of alley access to property

       Grvl	Gravel
       Pave	Paved
       NA 	No alley access
		
LotShape: General shape of property

       Reg	Regular	
       IR1	Slightly irregular
       IR2	Moderately Irregular
       IR3	Irregular
       
LandContour: Flatness of the property

       Lvl	Near Flat/Level	
       Bnk	Banked - Quick and significant rise from street grade to building
       HLS	Hillside - Significant slope from side to side
       Low	Depression
		
Utilities: Type of utilities available
		
       AllPub	All public Utilities (E,G,W,& S)	
       NoSewr	Electricity, Gas, and Water (Septic Tank)
       NoSeWa	Electricity and Gas Only
       ELO	Electricity only	
	
LotConfig: Lot configuration

       Inside	Inside lot
       Corner	Corner lot
       CulDSac	Cul-de-sac
       FR2	Frontage on 2 sides of property
       FR3	Frontage on 3 sides of property
	
LandSlope: Slope of property
		
       Gtl	Gentle slope
       Mod	Moderate Slope	
       Sev	Severe Slope
	
Neighborhood: Physical locations within Ames city limits

       Blmngtn	Bloomington Heights
       Blueste	Bluestem
       BrDale	Briardale
       BrkSide	Brookside
       ClearCr	Clear Creek
       CollgCr	College Creek
       Crawfor	Crawford
       Edwards	Edwards
       Gilbert	Gilbert
       IDOTRR	Iowa DOT and Rail Road
       MeadowV	Meadow Village
       Mitchel	Mitchell
       Names	North Ames
       NoRidge	Northridge
       NPkVill	Northpark Villa
       NridgHt	Northridge Heights
       NWAmes	Northwest Ames
       OldTown	Old Town
       SWISU	South & West of Iowa State University
       Sawyer	Sawyer
       SawyerW	Sawyer West
       Somerst	Somerset
       StoneBr	Stone Brook
       Timber	Timberland
       Veenker	Veenker
			
Condition1: Proximity to various conditions
	
       Artery	Adjacent to arterial street
       Feedr	Adjacent to feeder street	
       Norm	Normal	
       RRNn	Within 200' of North-South Railroad
       RRAn	Adjacent to North-South Railroad
       PosN	Near positive off-site feature--park, greenbelt, etc.
       PosA	Adjacent to postive off-site feature
       RRNe	Within 200' of East-West Railroad
       RRAe	Adjacent to East-West Railroad
	
Condition2: Proximity to various conditions (if more than one is present)
		
       Artery	Adjacent to arterial street
       Feedr	Adjacent to feeder street	
       Norm	Normal	
       RRNn	Within 200' of North-South Railroad
       RRAn	Adjacent to North-South Railroad
       PosN	Near positive off-site feature--park, greenbelt, etc.
       PosA	Adjacent to postive off-site feature
       RRNe	Within 200' of East-West Railroad
       RRAe	Adjacent to East-West Railroad
	
BldgType: Type of dwelling
		
       1Fam	Single-family Detached	
       2FmCon	Two-family Conversion; originally built as one-family dwelling
       Duplx	Duplex
       TwnhsE	Townhouse End Unit
       TwnhsI	Townhouse Inside Unit
	
HouseStyle: Style of dwelling
	
       1Story	One story
       1.5Fin	One and one-half story: 2nd level finished
       1.5Unf	One and one-half story: 2nd level unfinished
       2Story	Two story
       2.5Fin	Two and one-half story: 2nd level finished
       2.5Unf	Two and one-half story: 2nd level unfinished
       SFoyer	Split Foyer
       SLvl	Split Level
	
OverallQual: Rates the overall material and finish of the house

       10	Very Excellent
       9	Excellent
       8	Very Good
       7	Good
       6	Above Average
       5	Average
       4	Below Average
       3	Fair
       2	Poor
       1	Very Poor
	
OverallCond: Rates the overall condition of the house

       10	Very Excellent
       9	Excellent
       8	Very Good
       7	Good
       6	Above Average	
       5	Average
       4	Below Average	
       3	Fair
       2	Poor
       1	Very Poor
		
YearBuilt: Original construction date

YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)

RoofStyle: Type of roof

       Flat	Flat
       Gable	Gable
       Gambrel	Gabrel (Barn)
       Hip	Hip
       Mansard	Mansard
       Shed	Shed
		
RoofMatl: Roof material

       ClyTile	Clay or Tile
       CompShg	Standard (Composite) Shingle
       Membran	Membrane
       Metal	Metal
       Roll	Roll
       Tar&Grv	Gravel & Tar
       WdShake	Wood Shakes
       WdShngl	Wood Shingles
		
Exterior1st: Exterior covering on house

       AsbShng	Asbestos Shingles
       AsphShn	Asphalt Shingles
       BrkComm	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       CemntBd	Cement Board
       HdBoard	Hard Board
       ImStucc	Imitation Stucco
       MetalSd	Metal Siding
       Other	Other
       Plywood	Plywood
       PreCast	PreCast	
       Stone	Stone
       Stucco	Stucco
       VinylSd	Vinyl Siding
       Wd Sdng	Wood Siding
       WdShing	Wood Shingles
	
Exterior2nd: Exterior covering on house (if more than one material)

       AsbShng	Asbestos Shingles
       AsphShn	Asphalt Shingles
       BrkComm	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       CemntBd	Cement Board
       HdBoard	Hard Board
       ImStucc	Imitation Stucco
       MetalSd	Metal Siding
       Other	Other
       Plywood	Plywood
       PreCast	PreCast
       Stone	Stone
       Stucco	Stucco
       VinylSd	Vinyl Siding
       Wd Sdng	Wood Siding
       WdShing	Wood Shingles
	
MasVnrType: Masonry veneer type

       BrkCmn	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       None	None
       Stone	Stone
	
MasVnrArea: Masonry veneer area in square feet

ExterQual: Evaluates the quality of the material on the exterior 
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor
		
ExterCond: Evaluates the present condition of the material on the exterior
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor
		
Foundation: Type of foundation
		
       BrkTil	Brick & Tile
       CBlock	Cinder Block
       PConc	Poured Contrete	
       Slab	Slab
       Stone	Stone
       Wood	Wood
		
BsmtQual: Evaluates the height of the basement

       Ex	Excellent (100+ inches)	
       Gd	Good (90-99 inches)
       TA	Typical (80-89 inches)
       Fa	Fair (70-79 inches)
       Po	Poor (<70 inches
       NA	No Basement
		
BsmtCond: Evaluates the general condition of the basement

       Ex	Excellent
       Gd	Good
       TA	Typical - slight dampness allowed
       Fa	Fair - dampness or some cracking or settling
       Po	Poor - Severe cracking, settling, or wetness
       NA	No Basement
	
BsmtExposure: Refers to walkout or garden level walls

       Gd	Good Exposure
       Av	Average Exposure (split levels or foyers typically score average or above)	
       Mn	Mimimum Exposure
       No	No Exposure
       NA	No Basement
	
BsmtFinType1: Rating of basement finished area

       GLQ	Good Living Quarters
       ALQ	Average Living Quarters
       BLQ	Below Average Living Quarters	
       Rec	Average Rec Room
       LwQ	Low Quality
       Unf	Unfinshed
       NA	No Basement
		
BsmtFinSF1: Type 1 finished square feet

BsmtFinType2: Rating of basement finished area (if multiple types)

       GLQ	Good Living Quarters
       ALQ	Average Living Quarters
       BLQ	Below Average Living Quarters	
       Rec	Average Rec Room
       LwQ	Low Quality
       Unf	Unfinshed
       NA	No Basement

BsmtFinSF2: Type 2 finished square feet

BsmtUnfSF: Unfinished square feet of basement area

TotalBsmtSF: Total square feet of basement area

Heating: Type of heating
		
       Floor	Floor Furnace
       GasA	Gas forced warm air furnace
       GasW	Gas hot water or steam heat
       Grav	Gravity furnace	
       OthW	Hot water or steam heat other than gas
       Wall	Wall furnace
		
HeatingQC: Heating quality and condition

       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor
		
CentralAir: Central air conditioning

       N	No
       Y	Yes
		
Electrical: Electrical system

       SBrkr	Standard Circuit Breakers & Romex
       FuseA	Fuse Box over 60 AMP and all Romex wiring (Average)	
       FuseF	60 AMP Fuse Box and mostly Romex wiring (Fair)
       FuseP	60 AMP Fuse Box and mostly knob & tube wiring (poor)
       Mix	Mixed
		
1stFlrSF: First Floor square feet
 
2ndFlrSF: Second floor square feet

LowQualFinSF: Low quality finished square feet (all floors)

GrLivArea: Above grade (ground) living area square feet

BsmtFullBath: Basement full bathrooms

BsmtHalfBath: Basement half bathrooms

FullBath: Full bathrooms above grade

HalfBath: Half baths above grade

Bedroom: Bedrooms above grade (does NOT include basement bedrooms)

Kitchen: Kitchens above grade

KitchenQual: Kitchen quality

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       	
TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)

Functional: Home functionality (Assume typical unless deductions are warranted)

       Typ	Typical Functionality
       Min1	Minor Deductions 1
       Min2	Minor Deductions 2
       Mod	Moderate Deductions
       Maj1	Major Deductions 1
       Maj2	Major Deductions 2
       Sev	Severely Damaged
       Sal	Salvage only
		
Fireplaces: Number of fireplaces

FireplaceQu: Fireplace quality

       Ex	Excellent - Exceptional Masonry Fireplace
       Gd	Good - Masonry Fireplace in main level
       TA	Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement
       Fa	Fair - Prefabricated Fireplace in basement
       Po	Poor - Ben Franklin Stove
       NA	No Fireplace
		
GarageType: Garage location
		
       2Types	More than one type of garage
       Attchd	Attached to home
       Basment	Basement Garage
       BuiltIn	Built-In (Garage part of house - typically has room above garage)
       CarPort	Car Port
       Detchd	Detached from home
       NA	No Garage
		
GarageYrBlt: Year garage was built
		
GarageFinish: Interior finish of the garage

       Fin	Finished
       RFn	Rough Finished	
       Unf	Unfinished
       NA	No Garage
		
GarageCars: Size of garage in car capacity

GarageArea: Size of garage in square feet

GarageQual: Garage quality

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       NA	No Garage
		
GarageCond: Garage condition

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       NA	No Garage
		
PavedDrive: Paved driveway

       Y	Paved 
       P	Partial Pavement
       N	Dirt/Gravel
		
WoodDeckSF: Wood deck area in square feet

OpenPorchSF: Open porch area in square feet

EnclosedPorch: Enclosed porch area in square feet

3SsnPorch: Three season porch area in square feet

ScreenPorch: Screen porch area in square feet

PoolArea: Pool area in square feet

PoolQC: Pool quality
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       NA	No Pool
		
Fence: Fence quality
		
       GdPrv	Good Privacy
       MnPrv	Minimum Privacy
       GdWo	Good Wood
       MnWw	Minimum Wood/Wire
       NA	No Fence
	
MiscFeature: Miscellaneous feature not covered in other categories
		
       Elev	Elevator
       Gar2	2nd Garage (if not described in garage section)
       Othr	Other
       Shed	Shed (over 100 SF)
       TenC	Tennis Court
       NA	None
		
MiscVal: $Value of miscellaneous feature

MoSold: Month Sold (MM)

YrSold: Year Sold (YYYY)

SaleType: Type of sale
		
       WD 	Warranty Deed - Conventional
       CWD	Warranty Deed - Cash
       VWD	Warranty Deed - VA Loan
       New	Home just constructed and sold
       COD	Court Officer Deed/Estate
       Con	Contract 15% Down payment regular terms
       ConLw	Contract Low Down payment and low interest
       ConLI	Contract Low Interest
       ConLD	Contract Low Down
       Oth	Other
		
SaleCondition: Condition of sale

       Normal	Normal Sale
       Abnorml	Abnormal Sale -  trade, foreclosure, short sale
       AdjLand	Adjoining Land Purchase
       Alloca	Allocation - two linked properties with separate deeds, typically condo with a garage unit	
       Family	Sale between family members
       Partial	Home was not completed when last assessed (associated with New Homes)

# <font color=yellow>1 - Initial Data Exploration</font>

## <font color=green>1.1 - Importing Libraries</font>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('train.csv')

## <font color=green>1.2 - Exploring Data</font>

In [ ]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [ ]:
data.shape

(1460, 81)

In [ ]:
# Setting max of viewed columns on display
pd.set_option('display.max_columns', 85)

In [ ]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

### <font color=green>1.2.1 - Removing Columns: </font>
#### - 'MSSubClass' (Identifies the type of dwelling involved in the sale) - It is redundant with 'LandContour' field.

#### - 'GarageYrBlt' (Year garage was built) - The important thing is the current state (condition) of the garage.

#### - 'GarageQual' (Garage quality) - It is redundant with 'GarageCond: Garage condition' field.

In [ ]:
remove_columns = ['MSSubClass', 'GarageYrBlt', 'GarageQual']

In [ ]:
df = data.drop(remove_columns, axis=1)
df.shape

(1460, 78)

### <font color=green>1.2.2 - Verifying Data</font>

In [ ]:
# Farei uma varredura nas colunas para procurar inconsistências

lenth_df = len(df)

print('\033[1;4;33m-----  Lenth of DataFrame = {}\033[\n\n'.format(lenth_df))

for columns in df:
  analise_1 = data[columns].describe()
  analise_2 = data[columns].value_counts()
  contagem_1 = pd.value_counts(data[columns].isnull()) # Verifica e conta quantos campos são NaN (NULOS)
  contagem_2 = pd.value_counts(data[columns] == '')  # Verifica e conta quantos campos são VAZIOS
  print('\033[1;4;33mColumns Analise:  {} \033['.format(columns))
  print('\033[2;4;32m\n-----  Analysing with DESCRIBE:\033[\n{}'.format(analise_1))
  print('\033[2;4;32m\n-----  Analysing with VALUE_COUNTS:\033[\n{}'.format(analise_2))
  print('\033[2;4;32m\n-----  Analysing NULL FILDS = \033[{}'.format(lenth_df - contagem_1.loc[False]))
  print('\033[2;4;32m\n-----  Analysing EMPTY FILDS = \033[{}'.format(lenth_df - contagem_2.loc[False]))
  print('\n'+'  -----  <>' * 15 + '\n')

-----  Lenth of DataFrame = 1460[


Columns Analise:  Id [

-----  Analysing with DESCRIBE:[
count    1460.000000
mean      730.500000
std       421.610009
min         1.000000
25%       365.750000
50%       730.500000
75%      1095.250000
max      1460.000000
Name: Id, dtype: float64

-----  Analysing with VALUE_COUNTS:[
1       1
982     1
980     1
979     1
978     1
       ..
485     1
484     1
483     1
482     1
1460    1
Name: Id, Length: 1460, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  MSZoning [

-----  Analysing with DESCRIBE:[
count     1460
unique       5
top         RL
freq      1151
Name: MSZoning, dtype: object

-----  Analysing with VALUE_COUNTS:[
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  LotFrontage [

-----  Analysing with DESCRIBE:[
count    1201.000000
mean       70.049958
std        24.284752
min        21.000000
25%        59.000000
50%        69.000000
75%        80.000000
max       313.000000
Name: LotFrontage, dtype: float64

-----  Analysing with VALUE_COUNTS:[
60.0     143
70.0      70
80.0      69
50.0      57
75.0      53
        ...
137.0      1
141.0      1
38.0       1
140.0      1
46.0       1
Name: LotFrontage, Length: 110, dtype: int64

-----  Analysing NULL FILDS = [259

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  LotArea [

-----  Analysing with DESCRIBE:[
count      1460.000000
mean      10516.828082
std        9981.264932
min        1300.000000
25%        7553.500000
50%        9478.500000
75%       11601.500000
max      215245.000000
Name: LotArea, dtype: float64

-----  Analysing with VALUE_COUNTS:[
7200     25
9600     24
6000     17
9000     14
8400     14
         ..
14601     1
13682     1
4058      1
17104     1
9717      1
Name: LotArea, Length: 1073, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Street [

-----  Analysing with DESCRIBE:[
count     1460
unique       2
top       Pave
freq      1454
Name: Street, dtype: object

-----  Analysing with VALUE_COUNTS:[
Pave    1454
Grvl       6
Name: Street, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Alley [

-----  Analysing with DESCRIBE:[
count       91
unique       2
top       Grvl
freq        50
Name: Alley, dtype: object

-----  Analysing with VALUE_COUNTS:[
Grvl    50
Pave    41
Name: Alley, dtype: int64

-----  Analysing NULL FILDS = [1369

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  LotShape [

-----  Analysing with DESCRIBE:[
count     1460
unique       4
top        Reg
freq       925
Name: LotShape, dtype: object

-----  Analysing with VALUE_COUNTS:[
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  LandContour [

-----  Analysing with DESCRIBE:[
count     1460
unique       4
top        Lvl
freq      1311
Name: LandContour, dtype: object

-----  Analysing with VALUE_COUNTS:[
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Utilities [

-----  Analysing with DESCRIBE:[
count       1460
unique         2
top       AllPub
freq        1459
Name: Utilities, dtype: object

-----  Analysing with VALUE_COUNTS:[
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  LotConfig [

-----  Analysing with DESCRIBE:[
count       1460
unique         5
top       Inside
freq        1052
Name: LotConfig, dtype: object

-----  Analysing with VALUE_COUNTS:[
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  LandSlope [

-----  Analysing with DESCRIBE:[
count     1460
unique       3
top        Gtl
freq      1382
Name: LandSlope, dtype: object

-----  Analysing with VALUE_COUNTS:[
Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Neighborhood [

-----  Analysing with DESCRIBE:[
count      1460
unique       25
top       NAmes
freq        225
Name: Neighborhood, dtype: object

-----  Analysing with VALUE_COUNTS:[
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Condition1 [

-----  Analysing with DESCRIBE:[
count     1460
unique       9
top       Norm
freq      1260
Name: Condition1, dtype: object

-----  Analysing with VALUE_COUNTS:[
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Condition2 [

-----  Analysing with DESCRIBE:[
count     1460
unique       8
top       Norm
freq      1445
Name: Condition2, dtype: object

-----  Analysing with VALUE_COUNTS:[
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: Condition2, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  BldgType [

-----  Analysing with DESCRIBE:[
count     1460
unique       5
top       1Fam
freq      1220
Name: BldgType, dtype: object

-----  Analysing with VALUE_COUNTS:[
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  HouseStyle [

-----  Analysing with DESCRIBE:[
count       1460
unique         8
top       1Story
freq         726
Name: HouseStyle, dtype: object

-----  Analysing with VALUE_COUNTS:[
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  OverallQual [

-----  Analysing with DESCRIBE:[
count    1460.000000
mean        6.099315
std         1.382997
min         1.000000
25%         5.000000
50%         6.000000
75%         7.000000
max        10.000000
Name: OverallQual, dtype: float64

-----  Analysing with VALUE_COUNTS:[
5     397
6     374
7     319
8     168
4     116
9      43
3      20
10     18
2       3
1       2
Name: OverallQual, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  OverallCond [

-----  Analysing with DESCRIBE:[
count    1460.000000
mean        5.575342
std         1.112799
min         1.000000
25%         5.000000
50%         5.000000
75%         6.000000
max         9.000000
Name: OverallCond, dtype: float64

-----  Analysing with VALUE_COUNTS:[
5    821
6    252
7    205
8     72
4     57
3     25
9     22
2      5
1      1
Name: OverallCond, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  YearBuilt [

-----  Analysing with DESCRIBE:[
count    1460.000000
mean     1971.267808
std        30.202904
min      1872.000000
25%      1954.000000
50%      1973.000000
75%      2000.000000
max      2010.000000
Name: YearBuilt, dtype: float64

-----  Analysing with VALUE_COUNTS:[
2006    67
2005    64
2004    54
2007    49
2003    45
        ..
1875     1
1911     1
1917     1
1872     1
1905     1
Name: YearBuilt, Length: 112, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  YearRemodAdd [

-----  Analysing with DESCRIBE:[
count    1460.000000
mean     1984.865753
std        20.645407
min      1950.000000
25%      1967.000000
50%      1994.000000
75%      2004.000000
max      2010.000000
Name: YearRemodAdd, dtype: float64

-----  Analysing with VALUE_COUNTS:[
1950    178
2006     97
2007     76
2005     73
2004     62
       ...
2010      6
1986      5
1952      5
1983      5
1951      4
Name: YearRemodAdd, Length: 61, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  RoofStyle [

-----  Analysing with DESCRIBE:[
count      1460
unique        6
top       Gable
freq       1141
Name: RoofStyle, dtype: object

-----  Analysing with VALUE_COUNTS:[
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  RoofMatl [

-----  Analysing with DESCRIBE:[
count        1460
unique          8
top       CompShg
freq         1434
Name: RoofMatl, dtype: object

-----  Analysing with VALUE_COUNTS:[
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: RoofMatl, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Exterior1st [

-----  Analysing with DESCRIBE:[
count        1460
unique         15
top       VinylSd
freq          515
Name: Exterior1st, dtype: object

-----  Analysing with VALUE_COUNTS:[
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: Exterior1st, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Exterior2nd [

-----  Analysing with DESCRIBE:[
count        1460
unique         16
top       VinylSd
freq          504
Name: Exterior2nd, dtype: object

-----  Analysing with VALUE_COUNTS:[
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: Exterior2nd, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  MasVnrType [

-----  Analysing with DESCRIBE:[
count     1452
unique       4
top       None
freq       864
Name: MasVnrType, dtype: object

-----  Analysing with VALUE_COUNTS:[
None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

-----  Analysing NULL FILDS = [8

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  MasVnrArea [

-----  Analysing with DESCRIBE:[
count    1452.000000
mean      103.685262
std       181.066207
min         0.000000
25%         0.000000
50%         0.000000
75%       166.000000
max      1600.000000
Name: MasVnrArea, dtype: float64

-----  Analysing with VALUE_COUNTS:[
0.0      861
180.0      8
72.0       8
108.0      8
120.0      7
        ...
562.0      1
89.0       1
921.0      1
762.0      1
119.0      1
Name: MasVnrArea, Length: 327, dtype: int64

-----  Analysing NULL FILDS = [8

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  ExterQual [

-----  Analysing with DESCRIBE:[
count     1460
unique       4
top         TA
freq       906
Name: ExterQual, dtype: object

-----  Analysing with VALUE_COUNTS:[
TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  ExterCond [

-----  Analysing with DESCRIBE:[
count     1460
unique       5
top         TA
freq      1282
Name: ExterCond, dtype: object

-----  Analysing with VALUE_COUNTS:[
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  Foundation [

-----  Analysing with DESCRIBE:[
count      1460
unique        6
top       PConc
freq        647
Name: Foundation, dtype: object

-----  Analysing with VALUE_COUNTS:[
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64

-----  Analysing NULL FILDS = [0

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  BsmtQual [

-----  Analysing with DESCRIBE:[
count     1423
unique       4
top         TA
freq       649
Name: BsmtQual, dtype: object

-----  Analysing with VALUE_COUNTS:[
TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

-----  Analysing NULL FILDS = [37

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  BsmtCond [

-----  Analysing with DESCRIBE:[
count     1423
unique       4
top         TA
freq      1311
Name: BsmtCond, dtype: object

-----  Analysing with VALUE_COUNTS:[
TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

-----  Analysing NULL FILDS = [37

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  BsmtExposure [

-----  Analysing with DESCRIBE:[
count     1422
unique       4
top         No
freq       953
Name: BsmtExposure, dtype: object

-----  Analysing with VALUE_COUNTS:[
No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

-----  Analysing NULL FILDS = [38

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  BsmtFinType1 [

-----  Analysing with DESCRIBE:[
count     1423
unique       6
top        Unf
freq       430
Name: BsmtFinType1, dtype: object

-----  Analysing with VALUE_COUNTS:[
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

-----  Analysing NULL FILDS = [37

-----  Analysing EMPTY FILDS = [0

  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>  -----  <>

Columns Analise:  BsmtFinSF1 [

-----  Analysing with DESCRIBE:[
count    1460.000000
mean      443.639726
std       456.098091
min         0.000000
25%         0.000000
50%       383.500000
75%       712.250000
max      5644.000000
Name: BsmtFinSF1, dtype: float64
